
theme: jekyll-theme-minimal

title:   'Réflexion Collective'
author:
  name: 'Jérémy Viau-Trudel'
description: >
  Blogue collaboratif à saveur sociale, politique et scientifique. N'hésitez pas à proposez vos textes [via github](https://github.com/jvtrudel/reflexion-collective), faire des corrections ou soulever des problèmes via les [*Issues*](https://github.com/jvtrudel/reflexion-collective/issues).
slogan: >
  Le politique n'est pas une lutte de pouvoir, mais une réflexion et une prise de décision collective.

exclude: [  readme.md, commentaires, articles, production, Gemfile, .gitignore, vendor]

url: http://reflexion-collective.jvtrudel.com

permalink: pretty
